# 中台生产环境
icar:
  url: https://ipathcar.imtpath.net
  appid: app7291118000
  secret: BP7A4BaDv4HplTL3u3eT9Ho7tyVrNjvU09F4vcB7T2x971C5bMwIGO0D3gu3FRuI

# 支付中心
ipay:
  configId: prodnewicar
  key: 039759C0-DD49-4D4E-B94F-00018A413E4C

huitong:
  needOrderNotify: false
  secretKey: 02d4c190b2b97b4e489006bcc289ce22  # 慧通商旅测试环境key
  authId: ipath
  keyPass: 123456
  address: https://openapi-cnpc-uat.hwht.com
  certFilePath: /etc/ht_public_test.cert     # 对方测试环境公钥
  pemFilePath: /etc/private_dev.pem          # 我们的dev私钥

ipath:
  specialCustomer: 302269344182469
  carLevelName: 舒适



mobileUrl: "https://devmobilev2.imtpath.net"
notifyUrl:
  notifyPay: https://gatewayv2.imtpath.net/api/v2/partner/order/notifyPay
  notifyPayRefund: https://gatewayv2.imtpath.net/api/v2/partner/order/notifyRefund

#平台/司机取消重新派单 开关
rePlaceOrderAfterCoreCancelSwitch: true

#支付
pay:
  url: https://ipay.imtpath.net/
  appId: wx194fac2cf4f0db91
  configId: newyqcxuat
  templeteId: 140998
  key: 63A98453-D18F-4E0F-A653-18E54195A149

serviceMessage:
  # 腾讯云推文模板id
  tencent:
    companyId: 248100731020642053
    # 流程操作通知
    processOperationNotificationTemplateId: uFBNefzbq03q5nfs0urgCxYo16TWwHb3QGApUBHVZds
  wpp:
    companyId: 258207578547291909
    # 流程操作通知
    processOperationNotificationTemplateId: uFBNefzbq03q5nfs0urgCxYo16TWwHb3QGApUBHVZds

# 赛诺菲 同步个人会议的企业id
sync:
  meeting:
    companyId: 209150421147584261

#是否开启灰度测试
grayTestSwitch: 
  settle: true
log:
  enabled: true
  level: 1
  url: https://devop.imtpath.net/stage-api/log/interface/save

company:
  merk: 210945406113154821
